apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    name: p9200
    targetPort: 9200
  - port: 9300
    name: p9300
    targetPort: 9300    
  selector:
    app: elasticsearch

---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elk 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      hostNetwork: false
      containers:
      - image: elasticsearch
        name: elasticsearch       
        ports:
        - containerPort: 9200 
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: els-data
      volumes:
        - name: els-data
          hostPath:
            path: /elk/els-data

      nodeSelector:
        nodeRole: data  


---
# Ingress 文件如下
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: elasticsearch
#  namespace: elk
#spec:
#  rules:
#  - host: els.cs.cloud.com
#    http:
#      paths:
#        - backend:
#            serviceName: "elasticsearch"
#            servicePort: 9200

  