apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
 
  selector:
    app: kibana

---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: elk 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      hostNetwork: false
      containers:
      - image: kibana
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        name: kibana       
        ports:
        - containerPort: 5601            
      nodeSelector:
        nodeName: data  

---
# Ingress 文件如下
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: elk
spec:
  rules:
  - host: kibana.cscloud.com
    http:
      paths:
        - backend:
            serviceName: "kibana"
            servicePort: 5601        