apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: sso 
spec:
  type: LoadBalancer
  ports:
  - port: 9980
    targetPort: 8080
  selector:
    app: keycloak

 #docker run --restart=always --name=sso.keycloak.server -d -p 9980:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin {{DOCKER_IMG_NAME}}

---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: keycloak
  namespace: sso 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      name: keycloak
      labels:
        app: keycloak
    spec:
      hostNetwork: false
      containers:
      - image: "10.39.101.226:5000/jboss/keycloak"
        name: keycloak
        ports:
        - containerPort: 8080
        env:
          - name: KEYCLOAK_USER
            value:  admin
          - name: KEYCLOAK_PASSWORD
            value: admin 
      nodeSelector:
        nodeName: caocentos7  
      
---
# Ingress 文件如下
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  namespace: sso
spec:
  rules:
  - host: "sso.cs.cloud.com"
    http:
      paths:
        - backend:
            serviceName: "keycloak"
            servicePort: 9980 
                    