apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: sso 
spec:
  type: LoadBalancer
  ports:
  - port: 9980
    targetPort: 8080
  selector:
    app: keycloak

 #docker run --restart=always --name=sso.keycloak.server -d -p 9980:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin {{DOCKER_IMG_NAME}}

---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: keycloak
  namespace: sso 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      name: keycloak
      labels:
        app: keycloak
    spec:
      hostNetwork: false
      volumes:
        - name: config
          configMap:
            name: keycloak-configmap  
        - name: "mysql-data"
          hostPath:
            path: "/cloud-data/keycloak-data"    
      containers:
        - image: mysql
          name: mysql
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: "mysql-data"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: keycloak 
            - name: MYSQL_USER
              value: keycloak      
            - name: MYSQL_PASSWORD
              value: keycloak      
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
          args:
            - --name mysql    
        - image: "jboss/keycloak"
          name: keycloak
#        volumeMounts:
#          - mountPath: "/opt/jboss/keycloak/standalone/configuration/standalone.xml"
#            name: "config"
#            subPath: standalone.xml
          ports:
            - containerPort: 8080
          env:
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin 
          args:
            - --link mysql:mysql  
      nodeSelector:
        nodeRole: mgr  
      
---
# Ingress 文件如下
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  namespace: sso
spec:
  rules:
  - host: "sso.cscloud.com"
    http:
      paths:
        - backend:
            serviceName: "keycloak"
            servicePort: 9980 
                    